name: "Container Package Cleanup Action"
description: "Cleans up old Docker images based on specified criteria."
inputs:
  threshold-days:
    description: "The number of days to keep docker images."
    default: "7"
  threshold-versions:
    description: "The number of latest SNAPSHOT versions to keep."
    default: "1"
  included-tags:
    description: "A comma-separated list of tags to include for deletion."
    default: ""
  excluded-tags:
    description: "A comma-separated list of tags to exclude from deletion."
    default: ""
  debug:
    description: "Enable debug mode."
    default: "true"
  dry-run:
    description: "Enable dry run mode."
    default: "false"
  package-type:
    description: "Type of cleanup to perform (e.g., 'docker', 'container')."
    default: "container"
  included-patterns:
    description: "A comma-separated list of patterns to include for deletion."
    default: ""
  excluded-patterns:
    description: "A comma-separated list of patterns to exclude from deletion."
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "edit"
  color: "yellow"