---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '2025.1-1.0.0'
        type: string
        description: 'Custom release version'
      publish:
        required: true
        type: boolean
        default: false
        description: 'Enable publish release?'

jobs:
  release:
    uses:  Netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      publish: ${{ github.event.inputs.publish }}
