name: "Tag Checker Action"
description: "Check a specified tag"
inputs:
  tag:
    description: "Tag name"
    required: true
outputs:
  exists:
    description: "True/False"
runs:
  using: "node16"
  main: "dist/index.js"
