name: "Extractmeta Data"
description: ""
inputs:
    ref:
        description: "Current branch or tag ref."
        required: false
    default-template:
        description: "Template to use."
        required: false
    config-file-path:
        description: "Path to the configuration file."
        required: false
    branch-template:
        description: ''
    dist-tags:
        description: "Tags to use."
        required: false
outputs:
    rendered-template:
        description: "Current timestamp."
    ref:
        description: "Current branch or tag ref."
    ref-name:
        description: "Current branch or tag name."
    date:
        description: "Current date."
    time:
        description: "Current time."
    timestamp:
        description: "Current timestamp."
    dist-tag:
        description: "Current tag."
    major:
        description: "Major version."
    minor:
        description: "Minor version."
    patch:
        description: "Patch version."
runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "edit"
  color: "yellow"