name: "Custom Event Action"
description: "Triggers a custom repository_dispatch event"
inputs:
  event_type:
    description: "The type of the custom event"
    required: true
  client_payload:
    description: "Payload to send with the event"
    required: false
    default: "{}"
  github-token:
    description: "GitHub Token"
    required: true
outputs:
  status:
    description: "Status of the dispatch request"
runs:
  using: "node16"
  main: "dist/index.js"
